CREATE TABLE [dbo].[AccountTb]
(
    
	UserId INT PRIMARY KEY IDENTITY(1,1),
    EN NVARCHAR(50),
    Name NVARCHAR(100),
    Salt NVARCHAR(256), 
    HashPassword NVARCHAR(256),  
    RoleId INT DEFAULT 99 NOT NULL,
    CreatingDate DATETIME DEFAULT GETDATE() NOT NULL
)
