CREATE TABLE [dbo].[AccountTb]
(
    
	UserId INT PRIMARY KEY IDENTITY(1,1),
    EN NVARCHAR(50) NOT NULL,
    Name NVARCHAR(50) NOT NULL,
    Salt NVARCHAR(100) NOT NULL,
    HashPassword NVARCHAR(100) NOT NULL,
    RoleId INT DEFAULT 99 NOT NULL,
    CreatingDate DATETIME DEFAULT GETDATE() NOT NULL
)
